### PR TITLE
Add option to use different item parameters for buildList

### PR DESCRIPTION
**Pull request by Gibzon69**
As per my suggestion here: https://github.com/stefanvermaas/factory-builder/issues/180
I need this functionality for the lib to be useful for me personally so I thought I just created a PR and hopefully if you think it's a good idea, it can be merged.

### CODE REVIEW

**Review by stefanvermaas — DISMISSED** [review]
LGTM! Nice addition. 

---

**EDIT:** Would you mind adding this to the readme? Also, I'm unsure why the tests didn't run, I'll look into it.

**Comment by tnypxl** [comment]
Is this going anywhere?

**Comment by Gibzon69** [comment]
> LGTM! Nice addition.
> 
> **EDIT:** Would you mind adding this to the readme? Also, I'm unsure why the tests didn't run, I'll look into it.

Hey,
I missed your edit completely and saw the request today. I have updated the readme and did a push.

**Comment by stefanvermaas** [comment]
Thanks a lot! I'll go ahead and merge the PR. Later today, I'll create a new version.

**Pull request merged**
